api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api import views, urls_auth

router = routers.DefaultRouter()
router.register(r'usuarios', views.UserViewSet)
router.register(r'grupos', views.GroupViewSet)
router.register(r'perfiles', views.PerfilViewSet)
router.register(r'rutas', views.RutaViewSet)
router.register(r'circuitos', views.CircuitoViewSet)
router.register(r'categorias', views.CategoriaViewSet)
router.register(r'lugares', views.LugarViewSet)
router.register(r'empresas', views.EmpresaViewSet)
# router.register(r'sexos', views.SexoViewSet)
router.register(r'subcategorias', views.SubcategoriaViewSet)

router.register(r'paises', views.PaisViewSet)
router.register(r'ciudades', views.CiudadViewSet)
router.register(r'coordenadas', views.CoordenadaViewSet)
router.register(r'rankings', views.RankingViewSet)
router.register(r'rankings_empresas', views.RankingEmpresaViewSet)
router.register(r'roles', views.RolViewSet)
router.register(r'galerias', views.GaleriaViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^', include(urls_auth))
]

poi/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib.auth import views
from backend.forms import LoginForm
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^', include('frontend.urls')),
	url(r'^plataforma/', include('backend.urls')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^api/', include('api.urls')),
	url(r'^plataforma/login/$', views.login, {'template_name': 'plataforma/login.html', 'authentication_form': LoginForm}),
	url(r'^plataforma/logout/$', views.logout, {'next_page': '/plataforma/login'}),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/models.py
# -*- coding: utf-8 -*- 
from django.db import models
from django.contrib.auth.models import User
from django_mongodb_engine.contrib import MongoDBManager
from djangotoolbox.fields import EmbeddedModelField, ListField
from .listfield import StringListField

class Nombre(models.Model):
	nombre_arabe = models.CharField(max_length=255, blank=True)
	nombre_chino = models.CharField(max_length=255, blank=True)
	nombre_espanol = models.CharField(max_length=255, blank=True)
	nombre_frances = models.CharField(max_length=255, blank=True)
	nombre_ingles = models.CharField(max_length=255, blank=True)
	nombre_ruso = models.CharField(max_length=255, blank=True)
	nombre_portuges = models.CharField(max_length=255, blank=True)
	def __unicode__(self):
		return u'{nombre_arabe: %s,nombre_chino: %s,nombre_espanol: %s,nombre_frances: %s,nombre_ingles: %s,nombre_ruso: %s,nombre_portuges: %s}' % (self.nombre_arabe, self.nombre_chino, self.nombre_espanol, self.nombre_frances, self.nombre_ingles, self.nombre_ruso, self.nombre_portuges)
	class Meta:
		verbose_name_plural = "Nombres"

class Descripcion(models.Model):
	descripcion_arabe = models.CharField(max_length=500, blank=True)
	descripcion_chino = models.CharField(max_length=500, blank=True)
	descripcion_espanol = models.CharField(max_length=500, blank=True)
	descripcion_frances = models.CharField(max_length=500, blank=True)
	descripcion_ingles = models.CharField(max_length=500, blank=True)
	descripcion_ruso = models.CharField(max_length=500, blank=True)
	descripcion_portuges = models.CharField(max_length=500, blank=True)
	def __unicode__(self):
		return u'{descripcion_arabe: %s, descripcion_chino: %s, descripcion_espanol: %s, descripcion_frances: %s, descripcion_ingles: %s, descripcion_ruso: %s, descripcion_portuges: %s}' % (descripcion_arabe, descripcion_chino, descripcion_espanol, descripcion_frances, descripcion_ingles, descripcion_ruso, descripcion_portuges)
	class Meta:
		verbose_name_plural = "Descripciones"

class Tag(models.Model):
	valor = models.CharField(max_length=255)
	def __unicode__(self):
		return u'%s' % self.valor
	class Meta:
		verbose_name_plural = "Tags"

class RedSocial(models.Model):
	link = models.CharField(max_length=255)
	def __unicode__(self):
		return u'%s' % self.link
	class Meta:
		verbose_name_plural = "Redes Sociales"

class Sexo(models.Model):
	valor_arabe = models.CharField(max_length=50, blank=True)
	valor_chino = models.CharField(max_length=50, blank=True)
	valor_espanol = models.CharField(max_length=50, blank=True)
	valor_frances = models.CharField(max_length=50, blank=True)
	valor_ingles = models.CharField(max_length=50, blank=True)
	valor_ruso = models.CharField(max_length=50, blank=True)
	valor_portuges = models.CharField(max_length=50, blank=True)
	def __unicode__(self):
		return u'{valor_arabe: %s,valor_chino: %s,valor_espanol: %s,valor_frances: %s,valor_ingles: %s,valor_ruso: %s,valor_portuges: %s}' % (self.valor_arabe, self.valor_chino, self.valor_espanol, self.valor_frances, self.valor_ingles, self.valor_ruso, self.valor_portuges)
	class Meta:
		verbose_name_plural = "Sexos"

class EmailField(ListField):
	def formfield(self, **kwargs):
		return models.Field.formfield(self, StringListField, **kwargs)

class Perfil(models.Model):
	usuario = models.ForeignKey(User)
	sexo = EmbeddedModelField(Sexo, blank=True, null=True)
	emails = EmailField()
	telefonos = ListField(blank=True, null=True)
	fecha_de_nac = models.DateField(auto_now=False,auto_now_add=False, blank=True, null=True)
	image = models.ImageField(upload_to='profiles/', blank=True, null=True)
	def __unicode__(self):
		return u'%s' % self.usuario
	class Meta:
		verbose_name_plural = "Perfiles"

class Categoria(models.Model):
	nombre = EmbeddedModelField(Nombre)
	descripcion = EmbeddedModelField(Descripcion)

	def __unicode__(self):
		return u'%s' % self.nombre
	class Meta:
		verbose_name_plural = "Categorías"

class Subcategoria(models.Model):
	nombre = EmbeddedModelField(Nombre)
	descripcion = EmbeddedModelField(Descripcion)
	categoria = models.ForeignKey(Categoria)

	def __unicode__(self):
		return u'%s' % self.nombre
	class Meta:
		verbose_name_plural = "Sub Categorías"

class Pais(models.Model):
	nombre = EmbeddedModelField(Nombre)

	def __unicode__(self):
		return str(self.nombre)
	class Meta:
		verbose_name_plural = "Países"

class Ciudad(models.Model):
	nombre = EmbeddedModelField(Nombre)
	pais = models.ForeignKey(Pais)

	def __unicode__(self):
		return u'%s' % self.nombre
	class Meta:
		verbose_name_plural = "Ciudades"

class Point(models.Model):
	latitude = models.FloatField()
	longtitude = models.FloatField()
	def __unicode__(self):
		return u'{latitude: %s , longitude: %s}' % (self.latitude, self.longtitude)
	class Meta:
		verbose_name_plural = "Puntos"

class Lugar(models.Model):
	nombre = EmbeddedModelField(Nombre)
	descripcion = EmbeddedModelField(Descripcion, null=True, blank=True)
	categoria = models.ForeignKey(Categoria, null=True, blank=True)
	ciudad = EmbeddedModelField(Ciudad, null=True, blank=True)
	location = EmbeddedModelField(Point, blank=True, null=True)
	objects = MongoDBManager()
	direccion = models.CharField(max_length=255, blank=True)
	icono = models.ImageField(upload_to='iconos/')
	portada = models.ImageField(upload_to='portadas/')
	sitio_web = models.CharField(max_length=500, blank=True)
	redes_sociales = ListField(EmbeddedModelField(RedSocial))
	fecha_de_creacion = models.DateTimeField(auto_now_add=True, blank=True)
	tags = EmbeddedModelField(Tag, null=True, blank=True)
	def __unicode__(self):
		return u'%s' % self.nombre
	class Meta:
		verbose_name_plural = "Lugares"

class Empresa(models.Model):
	nombre = EmbeddedModelField(Nombre)
	email = EmailField()
	telefonos = ListField(blank=True, null=True)
	descripcion = EmbeddedModelField(Descripcion)
	categoria = models.ForeignKey(Categoria, blank=True)
	ciudad = EmbeddedModelField(Ciudad, blank=True)
	direccion = models.CharField(max_length=255, blank=True)
	icono = models.ImageField(upload_to='iconos/')
	portada = models.ImageField(upload_to='portadas/')
	redes_sociales = ListField(EmbeddedModelField(RedSocial))
	sitio_web = models.CharField(max_length=500, blank=True)
	fecha_de_creacion = models.DateTimeField(auto_now_add=True, blank=True)
	tags = EmbeddedModelField(Tag)
	def __unicode__(self):
		return u'%s' % self.nombre
	class Meta:
		verbose_name_plural = "Empresas"

class Ruta(models.Model):
	nombre = EmbeddedModelField(Nombre)
	descripcion = EmbeddedModelField(Descripcion)
	ciudad = models.CharField(max_length=255)
	def __unicode__(self):
		return u'%s' % self.nombre
	class Meta:
		verbose_name_plural = "Rutas"

class Circuito(models.Model):
	nombre = EmbeddedModelField(Nombre)
	descripcion = EmbeddedModelField(Descripcion)
	ruta = models.ForeignKey(Ruta)
	lugares = models.ManyToManyField(Lugar)
	def __unicode__(self):
		return u'%s' % self.nombre
	class Meta:
		verbose_name_plural = "Circuitos"

class Coordenada(models.Model):
	location = EmbeddedModelField(Point)
	objects = MongoDBManager()
	empresa = models.ForeignKey(Empresa,null=True , blank=True)
	def __unicode__(self):
		return u'%s' % self.empresa
	class Meta:
		verbose_name_plural = "Coordenadas"

class Ranking(models.Model):
	lugar = models.ForeignKey(Lugar)
	usuario = models.ForeignKey(User)
	valor = models.IntegerField(default=0)
	def __unicode__(self):
		return u'%s' % self.lugar
	class Meta:
		verbose_name_plural = "Ranking"

class RankingEmpresa(models.Model):
	empresa = models.ForeignKey(Empresa)
	usuario = models.ForeignKey(User)
	valor = models.IntegerField(default=0)
	def __unicode__(self):
		return u'%s' % self.empresa
	class Meta:
		verbose_name_plural = "Ranking"

class Rol(models.Model):
	nombre = EmbeddedModelField(Nombre)
	descripcion = EmbeddedModelField(Descripcion)
	def __unicode__(self):
		return u'%s' % self.nombre
	class Meta:
		verbose_name_plural = "Roles"

class Permiso(models.Model):
	lugar = models.ForeignKey(Lugar)
	usuario = models.ForeignKey(User)
	rol = models.ForeignKey(Rol)
	def __unicode__(self):
		return u'%s' % self.usuario
	class Meta:
		verbose_name_plural = "Permisos"

class Galeria(models.Model):
	nombre = EmbeddedModelField(Nombre)
	alt = models.CharField(max_length=255)
	path = models.CharField(max_length=255)
	def __unicode__(self):
		return u'%s' % self.nombre
	class Meta:
		verbose_name_plural = "Galerías"

templates/plataforma/base.html
{% load static %}
{% csrf_token %}
<!DOCTYPE html>
<html lang="es-cl">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<!-- Meta, title, CSS, favicons, etc. -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>{% block title %}{% endblock %}</title>

	<!-- Bootstrap -->
	<link href="{% static "back/vendors/bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
	<!-- Font Awesome -->
	<link href="{% static "back/vendors/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
	<!-- NProgress -->
	<link href="{% static "back/vendors/nprogress/nprogress.css" %}" rel="stylesheet">
	<!-- jQuery custom content scroller -->
	<link href="{% static "back/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" %}" rel="stylesheet"/>
	<!-- PNotify -->
	<link href="{% static "back/vendors/pnotify/dist/pnotify.css" %}" rel="stylesheet">
	<link href="{% static "back/vendors/pnotify/dist/pnotify.buttons.css" %}" rel="stylesheet">
	<link href="{% static "back/vendors/pnotify/dist/pnotify.nonblock.css" %}" rel="stylesheet">
	<!-- Custom Theme Style -->
	<link href="{% static "back/build/css/custom.min.css" %}" rel="stylesheet">
	{% block css %}
	{% endblock %}
	<!-- jQuery -->
	<script src="{% static "back/vendors/jquery/dist/jquery.min.js" %}"></script>
	<!-- Ajax JS -->
	<script src="{% static "back/build/js/jquery.cookie.js" %}"></script>
	<script src="{% static "back/build/js/ajax.js" %}"></script>

</head>

<body class="nav-md">
	<div class="container body">
		<div class="main_container">
			<div class="col-md-3 left_col menu_fixed">
				<div class="left_col scroll-view">
					<div class="navbar nav_title" style="border: 0;">
						<a href="index.html" class="site_title"><i class="fa fa-map"></i> <span>Poi</span></a>
					</div>
					<div class="clearfix"></div>
					<!-- menu profile quick info -->
					<div class="profile">
						<div class="profile_pic">
							<img src="{{ perfil.imagen_perfil }}" alt="..." class="img-circle profile_img profile">
						</div>
						<div class="profile_info">
							<span>Bienvenido,</span>
							{% if user.is_authenticated %}
								<h2>{{ user.get_full_name }}</h2>
							{% endif %}
						</div>
					</div>
					<!-- /menu profile quick info -->

					<br />

					<!-- sidebar menu -->
					<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
						<div class="menu_section">
							<h3>General</h3>
							<ul class="nav side-menu">
								<li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="/plataforma/home/">Dashboard</a></li>
									</ul>
								</li>
							</ul>
							<ul class="nav side-menu">
								<li><a><i class="fa fa-map-marker"></i> Punto de interés <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="/plataforma/destinos/">Destinos</a></li>
										<li><a href="/plataforma/servicios/">Servicios</a></li>
										<li><a href="/plataforma/productos/">Productos</a></li>
										<li><a href="/plataforma/circuitos/">Circuitos</a></li>
										<li><a href="/plataforma/rutas/">Rutas</a></li>
									</ul>
								</li>
							</ul>
							<ul class="nav side-menu">
								<li><a><i class="fa fa-bar-chart"></i> Empresas <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="/plataforma/estadisticas/">Estadísticas</a></li>
										<li><a href="/plataforma/informes/">Informes</a></li>
										<li><a href="/plataforma/calendarios/">Calendarios</a></li>
									</ul>
								</li>
							</ul>
						</div>
					</div>
					<!-- /sidebar menu -->

					<!-- /menu footer buttons -->
					<div class="sidebar-footer hidden-small">
						<a data-toggle="tooltip" data-placement="top" title="Settings"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></a>
						<a data-toggle="tooltip" data-placement="top" title="FullScreen"><span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span></a>
						<a data-toggle="tooltip" data-placement="top" title="Lock"><span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span></a>
						<a href="{% url 'django.contrib.auth.views.logout' %}" data-toggle="tooltip" data-placement="top" title="Logout"><span class="glyphicon glyphicon-off" aria-hidden="true"></span></a>
					</div>
					<!-- /menu footer buttons -->
				</div>
			</div>

			<!-- top navigation -->
			<div class="top_nav">
				<div class="nav_menu">
					<nav>
						<div class="nav toggle">
							<a id="menu_toggle"><i class="fa fa-bars"></i></a>
						</div>
						<ul class="nav navbar-nav navbar-right">
							<li class="">
								<a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
									<img src="{{ perfil.imagen_perfil }}" alt="" class="profile">
									{% if user.is_authenticated %}
										{{ user.get_full_name }}
									{% endif %}
									<span class=" fa fa-angle-down"></span>
								</a>
								<ul class="dropdown-menu dropdown-usermenu pull-right">
									<li><a href="{% url 'backend.views.editarPerfil' %}"> Perfil</a></li>
									<li>
										<a href="javascript:;">
											<span class="badge bg-red pull-right">50%</span>
											<span>Configuración</span>
										</a>
									</li>
									<li><a href="javascript:;">Ayuda</a></li>
									<li><a href="{% url 'django.contrib.auth.views.logout' %}"><i class="fa fa-sign-out pull-right"></i> Cerrar Sesión</a></li>
								</ul>
							</li>
						</ul>
					</nav>
				</div>
			</div>
			<!-- /top navigation -->

			<!-- page content -->
			
			{% block content %}
			{% endblock %}


			<!-- /page content -->

			<!-- footer content -->
			<footer>
				<div class="pull-right">
					Poi - Created by <a href="https://oxidocs.com">Oxido Creative Studio</a>
				</div>
				<div class="clearfix"></div>
			</footer>
			<!-- /footer content -->
			</div>
	</div>

	<!-- Bootstrap -->
	<script src="{% static "back/vendors/bootstrap/dist/js/bootstrap.min.js" %}"></script>
	<!-- FastClick -->
	<script src="{% static "back/vendors/fastclick/lib/fastclick.js" %}"></script>
	<!-- NProgress -->
	<script src="{% static "back/vendors/nprogress/nprogress.js" %}"></script>
	<!-- jQuery custom content scroller -->
	<script src="{% static "back/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js" %}"></script>
	<!-- PNotify -->
    <script src="{% static "back/vendors/pnotify/dist/pnotify.js" %}"></script>
    <script src="{% static "back/vendors/pnotify/dist/pnotify.buttons.js" %}"></script>
    <script src="{% static "back/vendors/pnotify/dist/pnotify.nonblock.js" %}"></script>
    <!-- /PNotify -->

	<!-- Custom Theme Scripts -->
	<script src="{% static "back/build/js/custom.min.js" %}"></script>


	{% block javascript %}
	{% endblock %}

</body>

</html>

templates/plataforma/calendarios.html
{% extends 'plataforma/base.html' %}

{% block title %}Poi Plataforma | Calendario{% endblock %}

{% block css %}
{% endblock %}

{% block content %}

	<div class="right_col" role="main">
		<div class="">
			<div class="page-title">
				<div class="title_left">
					<h3>Fixed Sidebar <small> Just add class <strong>menu_fixed</strong></small></h3>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block javascript %}
{% endblock %}

templates/plataforma/circuitos.html
{% extends 'plataforma/base.html' %}

{% block title %}Poi Plataforma | Circuitos{% endblock %}

{% block css %}
{% endblock %}

{% block content %}

	<div class="right_col" role="main">
		<div class="">
			<div class="page-title">
				<div class="title_left">
					<h3>Fixed Sidebar <small> Just add class <strong>menu_fixed</strong></small></h3>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block javascript %}
{% endblock %}

templates/plataforma/destinos.html
{% extends 'plataforma/base.html' %}
{% load static %}

{% block title %}Poi Plataforma | Destinos{% endblock %}

{% block css %}
	<style type="text/css">.nav_menu{margin-bottom: 0px;}</style>
{% endblock %}

{% block content %}

	<!-- page content -->
		<div id="map"></div>
	<!-- /page content -->

{% endblock %}

{% block javascript %}	
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhj68UdS4_RWpK1k3xJzTqHzTQZmAccvU&libraries=drawing"&signed_in=true&libraries=drawing></script>
	<script src="{% static "back/build/js/geolocation-marker.js" %}"></script>
	<script src="{% static "back/build/js/map.js" %}"></script>	
{% endblock %}

templates/plataforma/editar_perfil.html
{% extends 'plataforma/base.html' %}
{% load static %}

{% block title %}Poi Plataforma | Home{% endblock %}

{% block css %}
	<!-- bootstrap-daterangepicker -->
	<link href="{% static "back/vendors/bootstrap-daterangepicker/daterangepicker.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}

	<div class="right_col" role="main">
		<div class="container">
			<div class="page-title">
				<div class="">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="x_panel">
								<div class="x_title">
									<h2>Perfil <small>Editando mi perfil</small></h2>
									<div class="clearfix"></div>
								</div>
								<div class="x_content">
									<form data-parsley-validate class="form-horizontal form-label-left send" enctype="multipart/form-data">
									{% csrf_token %}
										<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
											<div class="form-group">
												<label class="col-md-3 col-sm-3 col-xs-12 text-right">Nombre de usuario</label>
												<div class="col-md-9 col-sm-9 col-xs-12">
													<input id="username" name="username" class="form-control" type="text" value="{{ user.username }}" placeholder="Nombre de Usuario">
												</div>
											</div>
											<div class="form-group">
												<label class="control-label col-md-3 col-sm-3 col-xs-12">Nombres</label>
												<div class="col-md-9 col-sm-9 col-xs-12">
													<input id="nombres" name="nombres" class="form-control" type="text" value="{{user.first_name}}" placeholder="Nombres">
												</div>
											</div>
											<div class="form-group">
												<label class="control-label col-md-3 col-sm-3 col-xs-12">Apellidos</label>
												<div class="col-md-9 col-sm-9 col-xs-12">
													<input id="apellidos" name="apellidos" class="form-control" type="text" value="{{user.last_name}}" placeholder="Apellidos">
												</div>
											</div>
											<div class="form-group">
												<label class="text-right col-md-3 col-sm-3 col-xs-12">Correo electrónico</label>
												<div class="col-md-9 col-sm-9 col-xs-12">
													<input id="email" name="email" class="form-control" type="email" value="{{user.email}}" placeholder="email@email.cl">
												</div>
											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
											<div class="form-group">
												<label class="control-label col-md-3 col-sm-3 col-xs-12">Sexo</label>
												<div class="col-md-6 col-sm-6 col-xs-12">
													<div id="gender" class="btn-group" data-toggle="buttons">
														{% for sexo in perfil.sexos %}
															{% if sexo.valor_espanol = "Masculino" %}
																<label class="btn btn-default {% if perfil.full.sexo.valor_espanol = "Masculino" %} active {% endif %}" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
																	<input type="radio" name="sexo" value="{{ sexo.valor_espanol }}" {% if perfil.full.sexo.valor_espanol = "Masculino" %} checked="checked" {% endif %} > &nbsp; {{ sexo.valor_espanol }} &nbsp;
																</label>
															{% else %}
																<label class="btn btn-primary {% if perfil.full.sexo.valor_espanol = "Femenino" %} active {% endif %}"" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
																	<input type="radio" name="sexo" value="{{ sexo.valor_espanol }}" {% if perfil.full.sexo.valor_espanol = "Masculino" %} checked="checked" {% endif %}> &nbsp; {{ sexo.valor_espanol }} &nbsp;
																</label>
															{% endif %}
														{% endfor %}
													</div>
												</div>
											</div>
											<div class="form-group">
												<label class="text-right col-md-3	 col-sm-3 col-xs-12">Fecha de Nacimiento</label>
												<div class="col-md-9 col-sm-9 col-xs-12">
													<input id="id_fecha_de_nac" name="fecha_de_nac" type="text" class="form-control date-picker" value="{{perfil.full.fecha_de_nac}}">
												</div>
											</div>
											<div class="form-group">
												<label class="text-right col-md-3 col-sm-3 col-xs-12">Imagen de perfil</label>
												<div class="col-md-9 col-sm-9 col-xs-12">
													<input type="file" name="img_perfil" class="form-control">
												</div>
											</div>											
										</div>
										<div class="clearfix"></div>
										<div class="ln_solid"></div>
										<div class="form-group pull-right">
											<div class="col-lg-12 col-xs-12">
												<button type="button" class="btn btn-primary">Volver</button>
												<button type="submit" class="btn btn-success">Guardar Cambios</button>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block javascript %}

	<!-- bootstrap-daterangepicker -->
	<script src="{% static "back/vendors/moment/min/moment-with-locales.min.js" %}" ></script>
	<script src="{% static "back/vendors/bootstrap-daterangepicker/daterangepicker.js" %}" ></script>
	<!-- /bootstrap-daterangepicker -->
	<!--custom-->
	<script type="text/javascript" src="{% static "back/build/js/edit_profile.js" %}"></script>
	<!--/custom-->
	<script type="text/javascript">
		
	</script>
{% endblock %}

templates/plataforma/estadisticas.html
{% extends 'plataforma/base.html' %}

{% block title %}Poi Plataforma | Estadísticas{% endblock %}

{% block css %}
{% endblock %}

{% block content %}

	<div class="right_col" role="main">
		<div class="">
			<div class="page-title">
				<div class="title_left">
					<h3>Fixed Sidebar <small> Just add class <strong>menu_fixed</strong></small></h3>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block javascript %}
{% endblock %}

templates/plataforma/index.html
{% extends 'plataforma/base.html' %}

{% block title %}Poi Plataforma | Home{% endblock %}

{% block css %}
{% endblock %}

{% block content %}

	<div class="right_col" role="main">
		<div class="">
			<div class="page-title">
				<div class="title_left">
					<h3>Fixed Sidebar <small> Just add class <strong>menu_fixed</strong></small></h3>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block javascript %}
{% endblock %}

templates/plataforma/informes.html
{% extends 'plataforma/base.html' %}

{% block title %}Poi Plataforma | Informes{% endblock %}

{% block css %}
{% endblock %}

{% block content %}

	<div class="right_col" role="main">
		<div class="">
			<div class="page-title">
				<div class="title_left">
					<h3>Fixed Sidebar <small> Just add class <strong>menu_fixed</strong></small></h3>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block javascript %}
{% endblock %}